name: Carles Deploy to GitHub Pages

on:
  push:
    branches:
      - feature-header

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: .  # Root folder with your index.html

